import { readdir, readFile, stat } from "node:fs/promises";
import { join, dirname, basename } from "node:path";
import type { ControlCoverage, ControlSupportStatus, MigrationReport, VisualControl, VisualForm } from "../ir/types.js";
import { parseDesignerSource } from "./designerParser.js";
import { parseCodeBehind, attachMigrationHints, type CodeBehindInfo } from "./codeBehindParser.js";
import { parseResx, applyResxToProps, type ResxData } from "./resxParser.js";

export type ConvertSourceResult = {
  forms: VisualForm[];
  report: MigrationReport;
};

export type ConvertSourceOptions = {
  inlineUserControls?: boolean;
  baseKindMap?: Map<string, string>;
  controlProps?: Map<string, Array<{ name: string; type: string }>>;
  userControlDefs?: Map<string, VisualControl[]>;
};

export async function findDesignerFiles(inputPath: string): Promise<string[]> {
  const info = await stat(inputPath);
  if (info.isFile()) {
    return inputPath.endsWith(".Designer.cs") ? [inputPath] : [];
  }
  const files: string[] = [];
  await walk(inputPath, files);
  return files.sort();
}

export async function convertDesignerSources(inputPath: string, options: ConvertSourceOptions = {}): Promise<ConvertSourceResult> {
  const files = await findDesignerFiles(inputPath);
  const hierarchy = options.baseKindMap && options.controlProps
    ? { baseKindMap: options.baseKindMap, controlProps: options.controlProps }
    : await collectBaseKindMap(inputPath);
  const { baseKindMap, controlProps } = hierarchy;
  const userControlDefs = options.userControlDefs
    ?? await collectUserControlDefinitions(inputPath, baseKindMap);

  const forms: VisualForm[] = [];
  const reports: MigrationReport[] = [];

  for (const file of files) {
    const source = await readFile(file, "utf8");
    if (isAutoGenerated(source)) continue;
    const resxPath = findResxForDesigner(file);
    let resxData: ResxData | undefined;
    if (resxPath) {
      try {
        resxData = await parseResx(resxPath);
      } catch {
        // resx parse failure is non-fatal
      }
    }
    const result = parseDesignerSource(source, {
      sourcePath: file,
      baseKindMap,
      resxData,
      controlProps,
      userControlDefs,
      inlineUserControls: options.inlineUserControls,
    });
    const codeBehindPaths = await findCodeBehindFamily(file);
    const codeBehindInfos: CodeBehindInfo[] = [];
    for (const codeBehindPath of codeBehindPaths) {
      try {
        const cbSource = await readFile(codeBehindPath, "utf8");
        codeBehindInfos.push(parseCodeBehind(cbSource, codeBehindPath));
      } catch {
        // missing or unreadable code-behind is non-fatal
      }
    }
    const cb = mergeCodeBehindInfos(codeBehindInfos);
    // Always attach: even without code-behind, every wired event must become a
    // contract point (goal: 100% coverage). Missing hints fall back to unresolved.
    attachMigrationHints(result.form, cb);
    if (cb.layoutHints.length) result.form.runtimeLayoutHints = cb.layoutHints;
    if (cb.visibilityGroups.length) result.form.runtimeVisibilityGroups = cb.visibilityGroups;
    const controlBindings = validRuntimeControlBindings(result.form, cb);
    if (controlBindings.length) result.form.runtimeControlBindings = controlBindings;
    const tabNavigators = validRuntimeTabNavigators(result.form, cb);
    if (tabNavigators.length) result.form.runtimeTabNavigators = tabNavigators;
    applyRuntimeItemHints(result.form, cb);
    applyRuntimeValueHints(result.form, cb);
    applyRuntimeAppearanceHints(result.form, cb);
    applyPropertyGridHints(result.form, cb);
    if (cb.navigations.length) {
      // Drop false-positive navigations that target a menu/strip component:
      // `contextMenu.Show(point)` shows a popup at a location, not form navigation.
      // Strip components are non-visual (not in the control map), so detect them
      // directly from `new *Strip(...)` / `new *Menu*(...)` declarations in source.
      const stripNames = new Set<string>();
      for (const m of source.matchAll(/(?:this\.)?([A-Za-z_]\w*)\s*=\s*new\s+[A-Za-z_][\w.]*(?:MenuStrip|ContextMenuStrip|ToolStrip|StatusStrip)\s*\(/g)) {
        stripNames.add(m[1]);
      }
      const navs = cb.navigations.filter((n) => !stripNames.has(n.target));
      if (navs.length) result.form.navigations = navs;
    }
    // Bindings come from code-behind; also capture Designer-side BindingSource
    // data sources (`someBindingSource.DataSource = typeof(X)`), which live in the
    // .Designer.cs and target non-visual components not present in the control tree.
    const designerBindings: typeof cb.bindings = [];
    for (const m of source.matchAll(/(?:this\.)?([A-Za-z_]\w*)\s*\.\s*DataSource\s*=\s*(?:typeof\s*\(\s*([A-Za-z_][\w.]*)\s*\)|(?:this\.)?([A-Za-z_][\w.]*))/g)) {
      const ctrl = m[1];
      const ds = m[2] ? m[2].split(".").pop()! : (m[3] ?? "").split(".").pop()!;
      if (ds) designerBindings.push({ controlName: ctrl, dataSource: ds, kind: "DataSource" });
    }
    const allBindings = [...cb.bindings, ...designerBindings];
    const seenB = new Set<string>();
    const mergedBindings = allBindings.filter((b) => {
      const k = `${b.controlName}|${b.boundProperty ?? ""}|${b.kind}`;
      if (seenB.has(k)) return false;
      seenB.add(k);
      return true;
    });
    if (mergedBindings.length) result.form.bindings = mergedBindings;
    forms.push(result.form);
    reports.push(result.report);
  }

  return {
    forms,
    report: mergeReports(reports)
  };
}

function findResxForDesigner(designerPath: string): string | null {
  const dir = dirname(designerPath);
  const base = basename(designerPath).replace(/\.Designer\.cs$/i, "");
  return join(dir, base + ".resx");
}

async function findCodeBehindFamily(designerPath: string): Promise<string[]> {
  const dir = dirname(designerPath);
  const base = basename(designerPath).replace(/\.Designer\.cs$/i, "");
  const entries = await readdir(dir, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && (entry.name === `${base}.cs` || entry.name.startsWith(`${base}.`) && entry.name.endsWith(".cs")) && !/\.Designer\.cs$/i.test(entry.name))
    .map((entry) => join(dir, entry.name))
    .sort();
}

function mergeCodeBehindInfos(infos: CodeBehindInfo[]): CodeBehindInfo {
  const unique = <T>(items: T[], key: (item: T) => string): T[] => [...new Map(items.map((item) => [key(item), item])).values()];
  return {
    methods: unique(infos.flatMap((info) => info.methods), (item) => `${item.sourceFile}|${item.name}|${item.lineStart}`),
    handlers: unique(infos.flatMap((info) => info.handlers), (item) => `${item.sourceFile}|${item.handler}`),
    navigations: unique(infos.flatMap((info) => info.navigations), (item) => `${item.target}|${item.modal}|${item.fromHandler ?? ""}`),
    bindings: unique(infos.flatMap((info) => info.bindings), (item) => `${item.controlName}|${item.boundProperty ?? ""}|${item.kind}|${item.dataSource}`),
    layoutHints: unique(infos.flatMap((info) => info.layoutHints), (item) => item.kind === "reparent"
      ? `${item.kind}|${item.controlName}|${item.parentControlName}|${item.panel}`
      : `${item.kind}|${item.controlName}|${item.parentControlName}|${item.label}`),
    visibilityGroups: unique(infos.flatMap((info) => info.visibilityGroups), (item) =>
      item.variants.flatMap((variant) => variant.hiddenControls).sort().join("|")),
    controlBindings: unique(infos.flatMap((info) => info.controlBindings), (item) =>
      `${item.handler}|${item.targetControlName}|${item.targetProperty}|${item.sourceControlName}|${item.sourceProperty}|${Boolean(item.negated)}`),
    tabNavigators: unique(infos.flatMap((info) => info.tabNavigators), (item) =>
      `${item.navigatorControlName}|${item.property}|${item.tabControlName}`),
    itemHints: unique(infos.flatMap((info) => info.itemHints), (item) =>
      `${item.controlName}|${item.source.kind}|${item.source.typeName ?? ""}|${item.source.expression}`),
    appearanceHints: unique(infos.flatMap((info) => info.appearanceHints), (item) => `${item.controlName}|${item.property}|${item.value}`),
    propertyGridHints: unique(infos.flatMap((info) => info.propertyGridHints), (item) =>
      `${item.controlName}|${item.source.typeName ?? ""}|${item.source.expression}`),
    valueHints: unique(infos.flatMap((info) => info.valueHints), (item) =>
      `${item.controlName}|${item.source.property}|${item.source.sourceFile}|${item.source.line}`),
  };
}

function validRuntimeControlBindings(form: VisualForm, cb: CodeBehindInfo): NonNullable<VisualForm["runtimeControlBindings"]> {
  if (cb.controlBindings.length === 0) return [];
  const index = new Map<string, VisualControl>();
  const handlerEvents = new Map<string, Array<{ controlName: string; event: string }>>();
  const visit = (controls: VisualControl[]) => controls.forEach((control) => {
    index.set(control.name, control);
    for (const event of control.events) {
      const entries = handlerEvents.get(event.handler) ?? [];
      entries.push({ controlName: control.name, event: event.event });
      handlerEvents.set(event.handler, entries);
    }
    visit(control.children);
  });
  visit(form.controls);
  for (const event of form.events ?? []) {
    const entries = handlerEvents.get(event.handler) ?? [];
    entries.push({ controlName: form.name, event: event.event });
    handlerEvents.set(event.handler, entries);
  }

  return cb.controlBindings.flatMap((binding) => {
    if (!index.has(binding.sourceControlName) || !index.has(binding.targetControlName)) return [];
    return (handlerEvents.get(binding.handler) ?? []).flatMap((trigger) => {
      // Re-evaluate only when the control property actually driving the RHS is
      // the one whose event invoked this handler. A handler may also read
      // unrelated controls; turning those reads into live subscriptions would
      // invent behavior that WinForms never wired.
      if (trigger.controlName !== binding.sourceControlName) return [];
      const expectedEvent = binding.sourceProperty === "checked" ? /^(?:CheckedChanged|CheckStateChanged)$/i
        : new RegExp(`^${binding.sourceProperty}Changed$`, "i");
      if (!expectedEvent.test(trigger.event)) return [];
      return [{
        ...binding,
        triggerControlName: trigger.controlName,
        triggerEvent: trigger.event,
      }];
    });
  });
}

function validRuntimeTabNavigators(form: VisualForm, cb: CodeBehindInfo): CodeBehindInfo["tabNavigators"] {
  if (cb.tabNavigators.length === 0) return [];
  const index = new Map<string, VisualControl>();
  const visit = (controls: VisualControl[]) => controls.forEach((control) => {
    index.set(control.name, control);
    visit(control.children);
  });
  visit(form.controls);
  return cb.tabNavigators.filter((binding) => {
    const navigator = index.get(binding.navigatorControlName);
    const tabControl = index.get(binding.tabControlName);
    return Boolean(navigator && tabControl?.kind === "TabControl" && navigator !== tabControl);
  });
}

function applyRuntimeItemHints(form: VisualForm, cb: CodeBehindInfo): void {
  if (cb.itemHints.length === 0) return;
  const index = new Map<string, VisualControl>();
  const visit = (controls: VisualControl[]) => controls.forEach((control) => {
    index.set(control.name, control);
    visit(control.children);
  });
  visit(form.controls);

  for (const hint of cb.itemHints) {
    const control = index.get(hint.controlName);
    if (!control) continue;
    const sources = control.itemSources ?? [];
    if (!sources.some((source) => source.kind === hint.source.kind
      && source.typeName === hint.source.typeName
      && source.expression === hint.source.expression)) {
      sources.push(hint.source);
    }
    control.itemSources = sources;
  }
}

function applyRuntimeValueHints(form: VisualForm, cb: CodeBehindInfo): void {
  if (cb.valueHints.length === 0) return;
  const methodsByName = new Map<string, CodeBehindInfo["methods"]>();
  for (const method of cb.methods) {
    const bucket = methodsByName.get(method.name) ?? [];
    bucket.push(method);
    methodsByName.set(method.name, bucket);
  }
  const reachable = new Set<string>([form.name, "OnLoad", "OnShown"]);
  for (const event of form.events ?? []) {
    if (/^(?:Load|Shown)$/i.test(event.event)) reachable.add(event.handler);
  }
  const queue = [...reachable];
  while (queue.length > 0) {
    const methodName = queue.shift()!;
    for (const method of methodsByName.get(methodName) ?? []) {
      for (const symbol of method.calledSymbols) {
        const called = symbol.split(".").pop()!;
        if (!methodsByName.has(called) || reachable.has(called)) continue;
        reachable.add(called);
        queue.push(called);
      }
    }
  }

  const index = new Map<string, VisualControl>();
  const visit = (controls: VisualControl[]) => controls.forEach((control) => {
    index.set(control.name, control);
    visit(control.children);
  });
  visit(form.controls);
  for (const hint of cb.valueHints) {
    if (!reachable.has(hint.source.methodName)) continue;
    const control = index.get(hint.controlName);
    if (!control) continue;
    const sources = control.runtimeValueSources ?? [];
    if (!sources.some((source) => source.property === hint.source.property
      && source.sourceFile === hint.source.sourceFile && source.line === hint.source.line)) {
      sources.push(hint.source);
    }
    control.runtimeValueSources = sources;
  }
}

function applyRuntimeAppearanceHints(form: VisualForm, cb: CodeBehindInfo): void {
  const index = new Map<string, VisualControl>();
  const visit = (controls: VisualControl[]) => controls.forEach((control) => {
    index.set(control.name, control);
    visit(control.children);
  });
  visit(form.controls);
  for (const hint of cb.appearanceHints) {
    const control = index.get(hint.controlName);
    if (control) control.appearance[hint.property] = hint.value;
  }
}

function applyPropertyGridHints(form: VisualForm, cb: CodeBehindInfo): void {
  if (cb.propertyGridHints.length === 0) return;
  const index = new Map<string, VisualControl>();
  const visit = (controls: VisualControl[]) => controls.forEach((control) => {
    index.set(control.name, control);
    visit(control.children);
  });
  visit(form.controls);
  for (const hint of cb.propertyGridHints) {
    const control = index.get(hint.controlName);
    if (control?.kind !== "PropertyGrid") continue;
    // Prefer a source whose type could be proven over an untyped assignment.
    if (!control.propertyGridSource?.typeName || hint.source.typeName) control.propertyGridSource = hint.source;
  }
}

function isAutoGenerated(source: string): boolean {
  if (!/void\s+InitializeComponent\s*\(\s*\)/.test(source)) return true;
  if (/<auto-generated>/.test(source)) return true;
  if (/GeneratedCodeAttribute/.test(source)) return true;
  return false;
}

export async function collectBaseKindMap(inputPath: string): Promise<{ baseKindMap: Map<string, string>; controlProps: Map<string, Array<{ name: string; type: string }>> }> {
  const csFiles: string[] = [];
  const info = await stat(inputPath);
  if (info.isDirectory()) {
    await walkCs(inputPath, csFiles);
  } else if (inputPath.endsWith(".Designer.cs")) {
    // Single-form conversion already reads the matching code-behind for events.
    // Use that same family for inheritance and custom-control properties too, so
    // `FormX : ProjectFormBase` is not lost merely because the caller selected
    // one Designer file instead of scanning the whole project.
    csFiles.push(...await findCodeBehindFamily(inputPath));
  }

  const map = new Map<string, string>();
  const controlProps = new Map<string, Array<{ name: string; type: string }>>();
  const classPattern = /^\s*(?:(?:public|internal|protected|private|sealed|abstract|static|partial)\s+)*class\s+([A-Za-z_]\w*)\s*:\s*([A-Za-z_][\w.<>]*)/gm;
  const propPattern = /^\s*public\s+([A-Za-z_][\w.\[\]<>?]*)\s+([A-Za-z_]\w*)\s*(?:\{\s*get[^{]*\}|=|;)/gm;

  for (const file of csFiles) {
    const source = await readFile(file, "utf8");
    for (const match of source.matchAll(classPattern)) {
      const derived = match[1];
      const rawBase = match[2];
      const genericMatch = rawBase.match(/^([A-Za-z_][\w.]*)<([A-Za-z_][\w.]*)>$/);
      if (genericMatch) {
        const genericName = genericMatch[1].split(".").pop() ?? genericMatch[1];
        const typeArg = genericMatch[2].split(".").pop() ?? genericMatch[2];
        if (derived !== genericName) map.set(derived, genericName);
        if (derived !== typeArg) map.set(derived, typeArg);
        continue;
      }
      const base = rawBase.split(".").pop() ?? rawBase;
      if (derived !== base) map.set(derived, base);

      const classStart = match.index!;
      const nextClass = source.indexOf("\nclass ", classStart + 6);
      const classBody = nextClass === -1 ? source.slice(classStart) : source.slice(classStart, nextClass);
      const props: Array<{ name: string; type: string }> = [];
      for (const pm of classBody.matchAll(propPattern)) {
        const ptype = (pm[1].split(".").pop() ?? pm[1]).replace(/\?$/, "");
        const pname = pm[2];
        if (["GetHashCode", "Equals", "ToString", "GetType", "Dispose"].includes(pname)) continue;
        if (ptype === "void" || pname.startsWith("On")) continue;
        props.push({ name: pname, type: ptype });
      }
      if (props.length) controlProps.set(derived, props);
    }
  }
  return { baseKindMap: map, controlProps };
}

export async function collectUserControlDefinitions(
  inputPath: string,
  providedBaseKindMap?: Map<string, string>,
): Promise<Map<string, VisualControl[]>> {
  const csFiles: string[] = [];
  const info = await stat(inputPath);
  if (info.isDirectory()) await walkCs(inputPath, csFiles);
  const designerFiles: string[] = [];
  if (info.isDirectory()) {
    await walkDesigner(inputPath, designerFiles);
  } else if (inputPath.endsWith(".Designer.cs")) {
    designerFiles.push(inputPath);
  }
  const designerMap = new Map<string, string>();
  for (const df of designerFiles) {
    const baseName = basename(df).replace(/\.Designer\.cs$/i, "");
    designerMap.set(baseName, df);
  }

  const defs = new Map<string, VisualControl[]>();
  const baseKindMap = providedBaseKindMap ?? (await collectBaseKindMap(inputPath)).baseKindMap;
  // First: scan .cs files for direct OR indirect UserControl declarations.
  // Real projects commonly use chains such as FileStatusList -> GitModuleControl
  // -> GitExtensionsControl -> TranslatedControl -> UserControl.
  for (const file of csFiles) {
    const source = await readFile(file, "utf8");
    for (const classMatch of source.matchAll(/(?:partial\s+)?class\s+([A-Za-z_]\w*)\s*:\s*([A-Za-z_][\w.]*)/g)) {
      const className = classMatch[1];
      if (!inheritsFrom(className, "UserControl", baseKindMap)) continue;
      const designerPath = designerMap.get(className);
      if (!designerPath || defs.has(className)) continue;
      const designerSource = await readFile(designerPath, "utf8");
      const resxData = await readOptionalResx(designerPath);
      const miniForm = parseDesignerSource(designerSource, { sourcePath: designerPath, baseKindMap, resxData });
      if (miniForm.form.controls.length > 0) {
        defs.set(className, miniForm.form.controls);
      }
    }
  }
  // Second: heuristic for Designer.cs files without explicit base class declaration
  for (const [className, designerPath] of designerMap) {
    if (defs.has(className)) continue;
    // A Form whose ClientSize happens to live in resx must never become a
    // shared UserControl merely because its Designer file lacks a direct
    // ClientSize assignment.
    if (inheritsFrom(className, "Form", baseKindMap)) continue;
    const designerSource = await readFile(designerPath, "utf8");
    const resxData = await readOptionalResx(designerPath);
    const hasClientSize = /this\.ClientSize\s*=/.test(designerSource)
      || Boolean(resxData?.get("$this")?.has("ClientSize"));
    const hasInitializeComponent = /void\s+InitializeComponent/.test(designerSource);
    const hasControlsAdd = /Controls\.Add/.test(designerSource);
    // UserControl Designer: has InitializeComponent + Controls.Add but NO clientSize
    // Form Designer: has ALL THREE (InitializeComponent, Controls.Add, ClientSize)
    if (hasInitializeComponent && hasControlsAdd && !hasClientSize) {
      const miniForm = parseDesignerSource(designerSource, { sourcePath: designerPath, baseKindMap, resxData });
      if (miniForm.form.controls.length > 0) defs.set(className, miniForm.form.controls);
    }
  }
  return defs;
}

async function readOptionalResx(designerPath: string): Promise<ResxData | undefined> {
  try {
    return await parseResx(findResxForDesigner(designerPath)!);
  } catch {
    return undefined;
  }
}

export function inheritsFrom(typeName: string, baseName: string, baseKindMap: Map<string, string>): boolean {
  let current = typeName;
  const seen = new Set<string>();
  while (!seen.has(current)) {
    if (current === baseName) return true;
    seen.add(current);
    const next = baseKindMap.get(current);
    if (!next) return false;
    current = next;
  }
  return false;
}

async function walkDesigner(dir: string, files: string[]) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === "bin" || entry.name === "obj" || entry.name === ".git") continue;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) await walkDesigner(fullPath, files);
    else if (entry.isFile() && entry.name.endsWith(".Designer.cs")) files.push(fullPath);
  }
}



async function walkCs(dir: string, files: string[]) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === "bin" || entry.name === "obj" || entry.name === ".git") continue;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) await walkCs(fullPath, files);
    else if (entry.isFile() && entry.name.endsWith(".cs") && !entry.name.endsWith(".Designer.cs")) files.push(fullPath);
  }
}

async function walk(dir: string, files: string[]) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === "bin" || entry.name === "obj" || entry.name === ".git") continue;
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      await walk(fullPath, files);
    } else if (entry.isFile() && entry.name.endsWith(".Designer.cs")) {
      files.push(fullPath);
    }
  }
}

function mergeReports(reports: MigrationReport[]): MigrationReport {
  const supportedControls = new Set<string>();
  const degradedControls = new Set<string>();
  const unknownControls = new Set<string>();
  return {
    sourceFiles: reports.flatMap((report) => report.sourceFiles),
    forms: reports.flatMap((report) => report.forms),
    formsConverted: reports.reduce((total, report) => total + report.formsConverted, 0),
    controlsConverted: reports.reduce((total, report) => total + report.controlsConverted, 0),
    supportedControls: mergeSet(reports, "supportedControls", supportedControls),
    degradedControls: mergeSet(reports, "degradedControls", degradedControls),
    unknownControls: mergeSet(reports, "unknownControls", unknownControls),
    controlCoverage: mergeControlCoverage(reports),
    eventStubs: reports.flatMap((report) => report.eventStubs)
  };
}

function mergeSet(
  reports: MigrationReport[],
  key: "supportedControls" | "degradedControls" | "unknownControls",
  target: Set<string>
): string[] {
  for (const report of reports) {
    for (const value of report[key]) target.add(value);
  }
  return [...target].sort();
}

function mergeControlCoverage(reports: MigrationReport[]): ControlCoverage {
  const counts = new Map<string, { count: number; status: ControlSupportStatus }>();

  for (const report of reports) {
    for (const item of report.controlCoverage.byKind) {
      const existing = counts.get(item.kind);
      counts.set(item.kind, {
        count: (existing?.count ?? 0) + item.count,
        status: mergeStatus(existing?.status, item.status)
      });
    }
  }

  let supported = 0;
  let degraded = 0;
  let unknown = 0;
  const byKind = [...counts.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([kind, value]) => {
      if (value.status === "supported") supported += value.count;
      if (value.status === "degraded") degraded += value.count;
      if (value.status === "unknown") unknown += value.count;
      return { kind, count: value.count, status: value.status };
    });

  const total = supported + degraded + unknown;
  return {
    total,
    supported,
    degraded,
    unknown,
    supportedPercent: percentage(supported, total),
    previewablePercent: percentage(supported + degraded, total),
    unknownPercent: percentage(unknown, total),
    byKind
  };
}

function mergeStatus(left: ControlSupportStatus | undefined, right: ControlSupportStatus): ControlSupportStatus {
  if (!left) return right;
  if (left === "unknown" || right === "unknown") return "unknown";
  if (left === "degraded" || right === "degraded") return "degraded";
  return "supported";
}

function percentage(part: number, total: number): number {
  if (total === 0) return 0;
  return Number(((part / total) * 100).toFixed(1));
}
