#!/usr/bin/env bash
# Whole-repo bulk validation: gather EVERY form .Designer.cs (+ sibling .cs) from a
# WinForms project and verify the two hard goal criteria across the entire set —
# product compiles (tsc --noEmit) and 100% event contract coverage.
#
# Two modes:
#   Remote:  bash scripts/validate-repo.sh <owner/repo> [branch] [max_forms]
#            e.g. bash scripts/validate-repo.sh gitextensions/gitextensions master 40
#   Local:   bash scripts/validate-repo.sh /path/to/local/winforms/project
#            (validates a local checkout — works offline, no GitHub API needed)
# Requires: python3, node build (+ network for remote mode).
set -euo pipefail

TARGET="${1:?usage: validate-repo.sh <owner/repo>|<local-dir> [branch] [max_forms]}"
BRANCH="${2:-master}"
MAX="${3:-40}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
npm run build >/dev/null

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$WORK/src"

if [ -d "$TARGET" ]; then
  # ---- Local mode: gather .Designer.cs (+ sibling .cs) from a local directory ----
  echo "Gathering form designers from local dir $TARGET ..."
  count=0
  while IFS= read -r p; do
    [ -z "$p" ] && continue
    case "$p" in
      *Resources.Designer.cs|*Settings.Designer.cs|*Language.Designer.cs) continue ;;
      */Properties/*) continue ;;
    esac
    rel="${p#"$TARGET"/}"
    flat="$(echo "$rel" | sed 's#/#__#g')"
    base="${flat%.Designer.cs}"
    cp "$p" "$WORK/src/$flat" 2>/dev/null || continue
    count=$((count + 1))
    cb="${p%.Designer.cs}.cs"
    [ -f "$cb" ] && cp "$cb" "$WORK/src/${base}.cs" 2>/dev/null || true
    [ "$count" -ge "$MAX" ] && break
  done < <(find "$TARGET" -name '*.Designer.cs' -not -path '*/bin/*' -not -path '*/obj/*' 2>/dev/null | sort)
  echo "Gathered $count form designer(s)."
  if [ "$count" -eq 0 ]; then echo "No form designers found under $TARGET."; exit 1; fi
else
  # ---- Remote mode: fetch from GitHub via tree API ----
  REPO="$TARGET"
  echo "Discovering form designers in $REPO@$BRANCH ..."
  # List all non-resource .Designer.cs paths via the git tree API.
  PATHS="$(curl -fsSL "https://api.github.com/repos/$REPO/git/trees/$BRANCH?recursive=1" \
    | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
except Exception:
    sys.stderr.write('GitHub tree API returned no JSON (rate-limited? wrong branch?). '
                     'Check: curl https://api.github.com/rate_limit\n')
    sys.exit(2)
if 'tree' not in d:
    sys.stderr.write('No git tree in API response: %s\n' % str(d.get('message', d))[:120])
    sys.exit(2)
ps = [t['path'] for t in d.get('tree', [])
      if t['path'].endswith('.Designer.cs')
      and 'Resources' not in t['path']
      and '/Properties/' not in t['path']
      and not t['path'].endswith('Settings.Designer.cs')
      and not t['path'].endswith('Language.Designer.cs')]
print('\n'.join(ps[:$MAX]))
")"

if [ -z "$PATHS" ]; then echo "No form designers found (or API rate-limited)."; exit 1; fi

RAW="https://raw.githubusercontent.com/$REPO/$BRANCH"
count=0
while IFS= read -r p; do
  [ -z "$p" ] && continue
  # Flatten path to a unique filename so same-named forms in different dirs don't clash.
  flat="$(echo "$p" | sed 's#/#__#g')"
  base="${flat%.Designer.cs}"
  if curl -fsSL "$RAW/$p" -o "$WORK/src/$flat" 2>/dev/null && [ -s "$WORK/src/$flat" ]; then
    count=$((count + 1))
    cbpath="${p%.Designer.cs}.cs"
    curl -fsSL "$RAW/$cbpath" -o "$WORK/src/${base}.cs" 2>/dev/null || true
  else
    rm -f "$WORK/src/$flat"
  fi
done <<< "$PATHS"
echo "Fetched $count form designer(s)."
fi

node dist/cli.js convert "$WORK" --out "$WORK/out"

echo "=== product tsc ==="
( cd "$WORK/out" && npm install --silent --no-audit --no-fund >/dev/null 2>&1 && npx tsc --noEmit -p tsconfig.json )
echo "product compiles: OK"

echo "=== event coverage across all forms ==="
python3 - "$WORK" <<'PY'
import re, glob, os, sys, json
work = sys.argv[1]
src = set()
for f in glob.glob(os.path.join(work, "src", "*.Designer.cs")):
    txt = open(f, encoding="utf-8", errors="replace").read()
    if "<auto-generated>" in txt:
        continue
    # Derive the form name from the actual class, not the (flattened) filename.
    cm = re.search(r'partial\s+class\s+([A-Za-z_]\w*)', txt)
    form = cm.group(1) if cm else os.path.basename(f).replace(".Designer.cs", "")
    for m in re.finditer(r'(?:this\.)?([A-Za-z_]\w*)\.([A-Za-z]+)\s*\+=', txt):
        c, e = m.group(1), m.group(2)
        src.add(f"{form}.{e}" if c in (form, "this") else f"{c}.{e}")
    for m in re.finditer(r'this\.([A-Za-z]+)\s*\+=', txt):
        src.add(f"{form}.{m.group(1)}")
mig = set()
for line in open(os.path.join(work, "out", "MIGRATION.md")):
    m = re.match(r'- \[ \] ([A-Za-z_0-9]+)\.([A-Za-z]+)', line)
    if m:
        mig.add(f"{m.group(1)}.{m.group(2)}")
ctrls = 0
for j in glob.glob(os.path.join(work, "out", "forms", "*.json")):
    d = json.load(open(j))
    def cnt(cs):
        return sum(1 + cnt(c.get("children", [])) for c in cs)
    ctrls += cnt(d["controls"])
missing = sorted(e for e in src if e not in mig)
if missing:
    print(f"COVERAGE GAP ({len(missing)} events missing):")
    print("\n".join(missing[:30]))
    sys.exit(1)
print(f"controls={ctrls} events={len(src)} coverage=100% (0 omissions)")
PY
echo "ALL FORMS IN $TARGET PASSED"
