/**
 * Curated preview data belongs to a visual profile, never to the shared
 * migration runtime.  The runtime consumes this structure without knowing
 * which WinForms project supplied it.
 */
export type WorkspacePreviewFixture = ReturnType<typeof gitExtensionsWorkspaceFixture>;

export function emptyWorkspacePreviewFixture() {
  return {
    enabled: false,
    applicationTitleFallback: "",
    repository: { name: "", branch: "", path: "", version: "", dirtyCount: 0 },
    revisions: [] as Record<string, unknown>[],
    diff: { variants: [] as Record<string, unknown>[], defaultBody: [] as Record<string, string>[], context: [] as Record<string, string>[], files: [] as Record<string, string>[] },
    menu: { triggerControlName: "", viewMenuName: "", items: [] as Record<string, unknown>[] },
    toolbar: {
      mainStripNames: [] as string[], scriptStripNames: [] as string[],
      textValues: {} as Record<string, string>, repositoryPathControlNames: [] as string[],
      repositoryBranchControlNames: [] as string[], dirtyCountControlNames: [] as string[],
      imageKeys: {} as Record<string, string>, actions: {} as Record<string, string>,
      showTextControlNames: [] as string[], scriptCommand: { title: "", label: "", imageKey: "" },
    },
    repositoryTree: { nodes: [] as Record<string, unknown>[], selectedId: "", collapsedIds: [] as string[], views: [] as Record<string, unknown>[] },
    revisionCommands: [] as Record<string, string>[],
    primaryRevisionRefs: [] as string[],
    fileTree: { files: [] as Record<string, unknown>[], selectedId: "", sources: {} as Record<string, string[]> },
    console: { title: "", banner: [] as string[], initialCommands: [] as string[], statusLines: [] as string[] },
    controlText: {} as Record<string, string>,
    controlGlyphs: [] as Array<{ pattern: string; glyph: string }>,
    toolbarTextPatterns: [] as string[],
    actionModes: [] as Array<{ pattern: string; title: string; detail: string }>,
    splitControls: {} as Record<string, { ratio: number; runtimeOrientation?: boolean; hideFirstPaneWithLeftPanel?: boolean }>,
    richTextPlaceholders: {} as Record<string, string>,
    stagedContextNames: [] as string[],
  };
}

export function gitExtensionsWorkspaceFixture() {
  return {
    enabled: true,
    applicationTitleFallback: "Git Extensions",
    repository: {
      name: "gitextensions_5",
      branch: "tmp/reword1",
      path: "C:\\dev\\gc\\gitextensions_5\\",
      version: "f0344e66 (tmp/go9-6)",
      dirtyCount: 1,
    },
    revisions: [
      { id: "worktree", graph: "status", refs: ["Working directory"], subject: "+ 1", author: "", email: "", committer: "", date: "", hash: "", parent: "9f9d9cf", artificial: true, statusIcon: "RepoStateDirty" },
      { id: "index", graph: "status", refs: ["Commit index"], subject: "", author: "", email: "", committer: "", date: "", hash: "", parent: "9f9d9cf", artificial: true, statusIcon: "RepoStateStaged" },
      { id: "25f6b60", graph: "main", refs: ["tmp/reword1"], subject: "Show multirevision diff also with no HEAD (#9947)", author: "Gerhard Olsson", email: "6248932+gerhardol@users.noreply.github.com", committer: "GitHub", date: "2022-04-29 21:14:28", hash: "25f6b60", parent: "f3e5c63", artificial: false },
      { id: "9f9d9cf", graph: "side", refs: ["master", "upstream/master"], subject: "Show multi revision diff also with no HEAD (#9947)", author: "Gerhard Olsson", email: "6248932+gerhardol@users.noreply.github.com", committer: "GitHub", date: "2022-04-29 21:14:28", hash: "9f9d9cf", fullHash: "9f9d9cf7c1ee11777197f6131024c0abd17d0e00", parent: "f3e5c63", artificial: false },
      { id: "f3e5c63", graph: "merge", refs: [], subject: "Left panel: reverted menu icon scaling", author: "Holger Schmidt", email: "hschmidt@users.noreply.github.com", committer: "Holger Schmidt", date: "2022-04-29 13:06:57", hash: "f3e5c63", parent: "14471c3", artificial: false },
      { id: "14471c3", graph: "main", refs: [], subject: "Show no changes in grid for artificial commits", author: "Gerhard Olsson", email: "6248932+gerhardol@users.noreply.github.com", committer: "Gerhard Olsson", date: "2022-04-29 00:43:21", hash: "14471c3", parent: "18d7ac4", artificial: false },
      { id: "18d7ac4", graph: "main", refs: ["v4.2.0"], subject: "Improve revision grid layout", author: "GitExtensions", email: "team@gitextensions.org", committer: "GitExtensions", date: "2022-04-28 18:35:04", hash: "18d7ac4", parent: "b42c0f1", artificial: false },
      { id: "b42c0f1", graph: "main", refs: [], subject: "Refresh repository objects after fetch", author: "Contributor", email: "contributor@users.noreply.github.com", committer: "Contributor", date: "2022-04-28 10:17:39", hash: "b42c0f1", parent: "830c2e7", artificial: false },
    ],
    diff: {
      variants: [
        { pattern: "Designer", body: [
          { old: "112", next: "112", text: "         RevisionsSplitContainer.Panel2.Controls.Add(RevisionInfo);", kind: "plain" },
          { old: "113", next: "", text: "-        CommitInfoTabPage.Controls.Add(RevisionInfo);", kind: "removed" },
          { old: "", next: "113", text: "+        RevisionInfo.Dock = DockStyle.Fill;", kind: "added" },
          { old: "114", next: "114", text: "         RightSplitContainer.Panel1.Controls.Add(RevisionsSplitContainer);", kind: "plain" },
        ] },
        { pattern: "RevisionGridControl", body: [
          { old: "418", next: "418", text: "     private void SetSelectedRevision(GitRevision revision)", kind: "plain" },
          { old: "419", next: "", text: "-        SelectedRevision = revision;", kind: "removed" },
          { old: "", next: "419", text: "+        SetSelectedRevision(revision, ensureVisible: true);", kind: "added" },
          { old: "420", next: "420", text: "     OnSelectionChanged(EventArgs.Empty);", kind: "plain" },
        ] },
      ],
      defaultBody: [
        { old: "114", next: "114", text: "     private void RefreshRevisions()", kind: "plain" },
        { old: "115", next: "", text: "-        RevisionGrid.RefreshRevisions();", kind: "removed" },
        { old: "", next: "115", text: "+        RevisionGrid.RefreshRevisions(keepSelection: true);", kind: "added" },
        { old: "116", next: "116", text: "     UpdateCommitDetails();", kind: "plain" },
      ],
      context: [
        { old: "117", next: "117", text: "     RefreshGitStatusMonitor();", kind: "plain" },
        { old: "118", next: "118", text: "     RevisionGrid.Focus();", kind: "plain" },
        { old: "119", next: "119", text: " }", kind: "plain" },
        { old: "120", next: "120", text: "", kind: "plain" },
        { old: "121", next: "121", text: " private void UpdateCommitDetails()", kind: "plain" },
        { old: "122", next: "122", text: " {", kind: "plain" },
        { old: "123", next: "123", text: "     if (RevisionGrid.SelectedRevision is null)", kind: "plain" },
        { old: "124", next: "124", text: "     {", kind: "plain" },
        { old: "125", next: "125", text: "         RevisionInfo.Clear();", kind: "plain" },
        { old: "126", next: "126", text: "         return;", kind: "plain" },
        { old: "127", next: "127", text: "     }", kind: "plain" },
        { old: "128", next: "128", text: "", kind: "plain" },
        { old: "129", next: "129", text: "     RevisionInfo.SetRevision(RevisionGrid.SelectedRevision);", kind: "plain" },
        { old: "130", next: "130", text: "     revisionDiff.SetRevision(RevisionGrid.SelectedRevision);", kind: "plain" },
        { old: "131", next: "131", text: " }", kind: "plain" },
      ],
      files: [
        { status: "M", imageKey: "FileStatusModified", path: "GitUI/CommandsDialogs/FormBrowse.cs" },
        { status: "M", imageKey: "FileStatusModified", path: "GitUI/CommandsDialogs/FormBrowse.Designer.cs" },
        { status: "A", imageKey: "FileStatusAdded", path: "GitUI/UserControls/RevisionGridControl.cs" },
      ],
    },
    menu: {
      triggerControlName: "repositoryToolStripMenuItem",
      viewMenuName: "viewRuntimeMenu",
      items: [
        { name: "fileToolStripMenuItem", text: "Start", children: ["Open repository…", "Clone repository…", "Exit"] },
        { name: "repositoryToolStripMenuItem", text: "Repository", children: [] },
        { name: "navigateRuntimeMenu", text: "Navigate", children: ["Back", "Forward", "Go to commit…"] },
        { name: "viewRuntimeMenu", text: "View", children: ["Show left panel", "Show split view", "Refresh"] },
        { name: "commandsToolStripMenuItem", text: "Commands", children: [] },
        { name: "_repositoryHostsToolStripMenuItem", text: "GitHub", children: [] },
        { name: "pluginsToolStripMenuItem", text: "Plugins", children: [] },
        { name: "toolsToolStripMenuItem", text: "Tools", children: ["Settings", "Manage hotkeys"] },
        { name: "helpToolStripMenuItem", text: "Help", children: ["About Git Extensions", "Documentation"] },
      ],
    },
    toolbar: {
      mainStripNames: ["ToolStripMain"],
      scriptStripNames: ["ToolStripScripts"],
      textValues: {},
      repositoryPathControlNames: ["_NO_TRANSLATE_WorkingDir"],
      repositoryBranchControlNames: ["branchSelect"],
      dirtyCountControlNames: ["toolStripButtonCommit"],
      imageKeys: { _NO_TRANSLATE_WorkingDir: "DashboardFolderGit" },
      actions: { toggleLeftPanel: "toggle-left-panel", toggleSplitViewLayout: "toggle-split-view" },
      showTextControlNames: ["_NO_TRANSLATE_WorkingDir", "branchSelect", "toolStripButtonCommit"],
      scriptCommand: { title: "Open repository in Visual Studio Code", label: "Open in VS Code", imageKey: "Develop" },
    },
    repositoryTree: {
      nodes: [
        { id: "submodules", parent: null, imageKey: "FolderSubmodule", label: "Submodules", level: 0, strong: true },
        { id: "repo", parent: "submodules", imageKey: "FolderSubmodule", label: "gitextensions_5 (tmp/reword1)", level: 1, strong: true },
        { id: "externals", parent: "repo", imageKey: "FolderOpen", label: "Externals", level: 2, strong: false },
        { id: "conemu", parent: "externals", imageKey: "FolderClosed", label: "conemu-inside", level: 3, strong: false },
        { id: "easyhook", parent: "externals", imageKey: "FolderClosed", label: "EasyHook", level: 3, strong: false },
        { id: "github", parent: "externals", imageKey: "FolderClosed", label: "Git.hub", level: 3, strong: false },
        { id: "texteditor", parent: "externals", imageKey: "FolderClosed", label: "ICSharpCode.TextEditor", level: 3, strong: false },
        { id: "branches", parent: null, imageKey: "FolderOpen", label: "Branches", level: 0, strong: true },
        { id: "tmp", parent: "branches", imageKey: "FolderOpen", label: "tmp", level: 1, strong: false },
        { id: "reword1", parent: "tmp", imageKey: "BranchLocal", label: "reword1", level: 2, strong: true },
        { id: "master", parent: "branches", imageKey: "BranchLocal", label: "master (0↑)", level: 1, strong: false },
        { id: "bugfix", parent: "branches", imageKey: "BranchLocal", label: "bugfix", level: 1, strong: false },
        { id: "feature", parent: "branches", imageKey: "BranchLocal", label: "feature", level: 1, strong: false },
        { id: "lazy", parent: "branches", imageKey: "BranchLocal", label: "lazyLoadIgnoredFiles_go (0↑)", level: 1, strong: false },
        { id: "remotes", parent: null, imageKey: "Remotes", label: "Remotes", level: 0, strong: true },
        { id: "origin", parent: "remotes", imageKey: "Remote", label: "origin", level: 1, strong: false },
        { id: "origin-master", parent: "origin", imageKey: "BranchRemote", label: "master", level: 2, strong: false },
        { id: "upstream", parent: "remotes", imageKey: "Remote", label: "upstream", level: 1, strong: false },
        { id: "upstream-master", parent: "upstream", imageKey: "BranchRemote", label: "master", level: 2, strong: false },
        { id: "inactive-remotes", parent: "remotes", imageKey: "Remote", label: "[Inactive]", level: 1, strong: false, muted: true },
        { id: "tags", parent: null, imageKey: "Tag", label: "Tags", level: 0, strong: true },
        { id: "v421", parent: "tags", imageKey: "Tag", label: "v4.2.1", level: 1, strong: false },
      ],
      selectedId: "reword1",
      collapsedIds: ["origin", "upstream", "tags"],
      views: [
        { title: "Repository tree", imageKey: "LayoutSidebarLeft", rootId: null },
        { title: "Branches", imageKey: "LayoutSidebarTopLeft", rootId: "branches" },
        { title: "Remotes", imageKey: "LayoutSidebarTopRight", rootId: "remotes" },
        { title: "Submodules", imageKey: "FolderSubmodule", rootId: "submodules" },
        { title: "Tags", imageKey: "Tag", rootId: "tags" },
      ],
    },
    revisionCommands: [
      { label: "Checkout revision…", imageKey: "Checkout", shortcut: "" },
      { label: "Create new branch…", imageKey: "BranchCreate", shortcut: "" },
      { label: "Cherry pick commit", imageKey: "CherryPick", shortcut: "" },
      { label: "Compare revisions", imageKey: "Diff", shortcut: "Ctrl+D" },
      { label: "Copy commit hash", imageKey: "CommitId", shortcut: "Ctrl+C" },
    ],
    primaryRevisionRefs: ["master", "reword1"],
    fileTree: {
      files: [
        { id: "src", parent: null, name: "src", path: "src", folder: true, level: 0 },
        { id: "commands", parent: "src", name: "CommandsDialogs", path: "src/CommandsDialogs", folder: true, level: 1 },
        { id: "browse", parent: "commands", name: "FormBrowse.cs", path: "GitUI/CommandsDialogs/FormBrowse.cs", folder: false, level: 2 },
        { id: "designer", parent: "commands", name: "FormBrowse.Designer.cs", path: "GitUI/CommandsDialogs/FormBrowse.Designer.cs", folder: false, level: 2 },
        { id: "grid", parent: "src", name: "RevisionGrid", path: "src/RevisionGrid", folder: true, level: 1 },
        { id: "grid-control", parent: "grid", name: "RevisionGridControl.cs", path: "GitUI/UserControls/RevisionGridControl.cs", folder: false, level: 2 },
        { id: "readme", parent: null, name: "README.md", path: "README.md", folder: false, level: 0 },
      ],
      selectedId: "browse",
      sources: {
        browse: ["using GitCommands;", "using GitUI.CommandsDialogs;", "", "public sealed partial class FormBrowse", "{", "    private void RefreshRevisions()", "    {", "        RevisionGrid.RefreshRevisions();", "    }", "}"],
        designer: ["partial class FormBrowse", "{", "    private SplitContainer MainSplitContainer;", "    private RevisionGridControl RevisionGrid;", "    private CommitInfo CommitInfo;", "", "    private void InitializeComponent()", "    {", "        RevisionGrid.Dock = DockStyle.Fill;", "    }", "}"],
        "grid-control": ["public sealed class RevisionGridControl : GitModuleControl", "{", "    public GitRevision? SelectedRevision { get; private set; }", "", "    public void RefreshRevisions(bool keepSelection)", "    {", "        // reload revision graph", "    }", "}"],
        readme: ["# Git Extensions", "", "Git Extensions is a graphical user interface for Git.", "", "This preview was reconstructed from WinForms metadata."],
      },
    },
    console: {
      title: "Console · gitextensions_5",
      banner: ["Microsoft Windows [Version 10.0.22631.4037]", "Git Extensions repository console"],
      initialCommands: ["git status --short", " M GitUI/CommandsDialogs/FormBrowse.cs", " M GitUI/CommandsDialogs/FormBrowse.Designer.cs"],
      statusLines: ["Changes not staged for commit:", "  modified: GitUI/CommandsDialogs/FormBrowse.cs"],
    },
    controlText: {
      commitAuthorStatus: "Author configured", toolStripStatusBranchIcon: "⑂", branchNameLabel: "master",
      remoteNameLabel: "origin/master", commitEndPadding: "", CommitAndPush: "Commit & push",
      btnResetAllChanges: "Reset all changes", btnResetUnstagedChanges: "Reset unstaged changes", btnRefresh: "Refresh",
      btnCollapseGroups: "Collapse groups", btnAsTree: "Tree view", btnByPath: "Group by path",
      btnByExtension: "Group by extension", btnByStatus: "Group by status", btnFindInFilesGitGrep: "Find in files",
      nextChangeButton: "Next change", previousChangeButton: "Previous change", increaseNumberOfLines: "More context",
      decreaseNumberOfLines: "Less context", showEntireFileButton: "Show entire file", settingsButton: "Settings",
      toolStageAllItem: "Stage all", toolUnstageAllItem: "Unstage all",
    },
    controlGlyphs: [
      { pattern: "commitandpush", glyph: "↗" }, { pattern: "commit", glyph: "✓" },
      { pattern: "unstage", glyph: "↑" }, { pattern: "stage", glyph: "↓" }, { pattern: "reset", glyph: "↶" },
      { pattern: "refresh", glyph: "↻" }, { pattern: "previous", glyph: "↑" }, { pattern: "next", glyph: "↓" },
      { pattern: "increase", glyph: "+" }, { pattern: "decrease", glyph: "−" }, { pattern: "find|search", glyph: "⌕" },
      { pattern: "toggleleft", glyph: "☰" }, { pattern: "togglesplit|commitinfoposition", glyph: "▥" },
      { pattern: "levelup", glyph: "↑" }, { pattern: "worktree|branch", glyph: "⑂" }, { pattern: "workingdir", glyph: "⌂" },
      { pattern: "pull", glyph: "↓" }, { pattern: "push", glyph: "↑" }, { pattern: "stash", glyph: "▣" },
      { pattern: "browse|open", glyph: "▤" }, { pattern: "terminal|console|shell", glyph: ">_" },
      { pattern: "explorer", glyph: "▧" }, { pattern: "settings|options", glyph: "⚙" },
      { pattern: "tree|path|extension|status", glyph: "▦" },
    ],
    toolbarTextPatterns: ["WorkingDir", "branchSelect", "ButtonCommit"],
    actionModes: [
      { pattern: "bisect", title: "Bisect in progress", detail: "Select good or bad revision to continue." },
      { pattern: ".*", title: "Git command in progress", detail: "The repository is being refreshed…" },
    ],
    splitControls: {
      MainSplitContainer: { ratio: .19, hideFirstPaneWithLeftPanel: true },
      RightSplitContainer: { ratio: .27, runtimeOrientation: true },
      RevisionsSplitContainer: { ratio: .55 },
    },
    richTextPlaceholders: { Message: "Enter commit message" },
    stagedContextNames: ["Staged"],
  };
}
